### ISSUE TITLE
Questions about evaluation

### ISSUE THREAD

**Issue by yan99033** [jczarnowski/DeepFactors#1]
Hi,

First of all, great work! I am looking forward to the release of the code. 

About the evaluation, I have some questions:
1. In Section VI C, the first paragraph explains the use of ground truth depth maps to evaluate the reconstruction accuracy. The next paragraph talks about the use of TUM benchmark scripts to scale the depth maps and the trajectory. However, In Table II, I can't find the ATE of those sequences. 
2. Also, Table III only shows the ATE but not the reconstruction error on another set of sequences. Is there a reason why do you have two different sets of sequences with two different metrics?
3. You did mention in the paper that you evaluated the reconstruction errors of the scaled depth map using SfMLearner code. But what I found in SfMLearner depth evaluation code is that each depth map is individually scaled according to the medians of the ground truth depth map and the predicted depth map, [see here](https://github.com/tinghuiz/SfMLearner/blob/2a387b763bc2b6f95b095f929bf751797c9db68a/kitti_eval/eval_depth.py#L66). Therefore, I am wondering how exactly did you evaluate the reconstruction errors. 

It would be great if you can share at least your evaluation code to minimise the discrepancy between the papers working on monocular dense reconstruction problems, given the fact that running SLAM is already non-deterministic on different machines. Thanks again.

**Comment by jczarnowski** [comment]
* For the ATE evaluation, we've focused on the TUM dataset as the standard benchmark and selected sequences to compare against the results published in the CNN-SLAM and DeepTAM papers. The code for these methods was not available to run. At the time, joint mapping and tracking implementation was not published for DeepTAM and CNN-SLAM is still not open source. Therefore, in the reconstruction evaluation table we've focused on reconstruction only.

* The reference to SfMLearner was to show that we follow the principle of scaling depth maps to compare them against the ground truth. We did not use the ground truth median as SfMLearner though, but for a more fair comparison we've used the 'optimal' scale estimated by the TUM script.

Comparing monocular SLAM systems is indeed hard, and there is a lot more experiments or axes we could compare on. That's why we will be releasing the full code together with the evaluation.

**Comment by yan99033** [comment]
> For the ATE evaluation, we've focused on the TUM dataset as the standard benchmark and selected sequences to compare against the results published in the CNN-SLAM and DeepTAM papers. The code for these methods was not available to run. At the time, joint mapping and tracking implementation was not published for DeepTAM and CNN-SLAM is still not open source. Therefore, in the reconstruction evaluation table we've focused on reconstruction only.

What I meant is that you can have both the reconstruction accuracy and the ATE evaluations in Table II, similar to Table 1 in CNN-SLAM. I am curious to find out if the reconstruction accuracy is proportional to the camera trajectory accuracy.

**Edit:** The reason why this is interesting is that you are using graph-based optimisation, which supposedly should give you better mapping and tracking performance; in contrast, CNN-SLAM uses alternating optimisation (tracking and then EKF-style depth fusion), which potentially can give you good tracking but bad mapping, or vice versa (compare ICL/office2 and ICL/living1 in Table 1 of CNN-SLAM).

> The reference to SfMLearner was to show that we follow the principle of scaling depth maps to compare them against the ground truth. We did not use the ground truth median as SfMLearner though, but for a more fair comparison we've used the 'optimal' scale estimated by the TUM script.

Got it. That makes sense.


Thanks again.
