### ISSUE TITLE
Saving the results

### ISSUE THREAD

**Issue by AbdulhamidObeid** [jczarnowski/DeepFactors#11]
Hello @jczarnowski 

I was wondering if there is a way to save the resulting 3d reconstructed model as a point cloud or any other file format, and if it would be a build up of all the frames

And would it be possible to modify deepfactors to add such functionality

**Comment by jczarnowski** [comment]
Hi @AbdulhamidObeid 

Unfortunately we don't have any code for directly saving a global model to a file. However, the system can save all keyframes together with their estimated depth and poses, so it should be easy to e.g. just read them in python and create a pointcloud by reprojecting all the keyframe pixels.

To save the keyframes try specifying: `-run_log_dir=results` in the parameters (either append to the command line or edit flagfiles). It will save the results of every run of the SLAM system under `results/<timestamp>`. You can find the keyframes in there.

As we're optimising for local consistency, the reprojected global maps will likely require post processing and merging in order to obtain a coherent reconstruction.
