### ISSUE TITLE
cudaError code: out of memory

### ISSUE THREAD

**Issue by yan99033** [jczarnowski/DeepFactors#2]
Thanks again for releasing the code. Great work!

I am running a modified version of your code. It is just a modification to make it run on Ubuntu 16.04.

However, I was wondering if it is normal that you are getting out-of-memory error on Ubuntu 18.04. I got 
> Exception in slam: CUDAException: Unable to cudaMallocPitch

I also observed that the GPU memory usage was getting higher and higher until it reached the maximum usage before the program crashed. I tested on a ScanNet sequence and a TUM RGBD sequence. 

Other than that, the point cloud output and camera tracking are pretty much the same as what I saw in the video and the screenshots. 
![deepfactor](https://user-images.githubusercontent.com/26388965/79683121-033c5180-81e5-11ea-8c33-904ffd9faee5.png)

**Comment by jczarnowski** [comment]
Thank you!

This is expected. The system consumes quite a lot of GPU memory because we need to fit both the neural network and the GPU buffers for CUDA based optimisation. After spawning too many keyframes for your GPU it will simply not be able to continue.  I ran the system on a GTX 1080 and with different settings for that specific scene to make it run through it. Limiting the number of keyframes spawned can help here.

**Comment by yan99033** [comment]
That makes sense. I was just hoping that I did not do something that caused this error.
