### ISSUE TITLE
How to reproduce the same results on TUM sequences?

### ISSUE THREAD

**Issue by JunjH** [jczarnowski/DeepFactors#21]
I've tried to reproduce the results on tum/360,desk,desk2,rpy,xyz, but couldn't get the same results. 
The following results were obtained by comparing the outputted keyframe trajectories with ground truths.
desk  0.228
desk2 0.324
360   0.304
rpy   0.091
xyz   0.054

Can you tell me how to reproduce the results given in the paper.

**Comment by jczarnowski** [comment]
Have you used the scale-adjusted ATE or just plain ATE?

If yes, then it's all about tuning the parameters. The ones that come by default are a tradeoff that works for different use cases that people running the repo might have.

Unfortunately I can't provide you with the old config as I changed jobs since
