### ISSUE TITLE
failed to load the pre training model

### ISSUE THREAD

**Issue by JHF0930** [jczarnowski/DeepFactors#29]
Hello, failed to load the pre training model. The environment is cuda11.4. What's the reason

> terminate called after throwing an instance of 'std::runtime_error'
> what():  Failed importing graph from: data/nets/scannet256_32_frozen.pb

**Comment by jczarnowski** [comment]
Unfortunately I am no longer maintaining this project due to restrictions of my current employment. Last time I tested the software was in our docker image, which uses `nvidia/cuda:10.0-cudnn7-devel` as the base image. I suppose you will have the best luck running the software if you switch to the CUDA and cudnn version from that image, or simply build and use the docker image.
